import type { MetadataRoute } from "next";

// PWA manifest — served at /manifest.webmanifest. Brand icons are generated by
// scripts/generate-brand-assets in the mobile repo (public/brand/icon-*.png).
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Take Me Pic",
    short_name: "Take Me Pic",
    description:
      "Trouve un voyageur sympa à proximité qui veut bien prendre la photo.",
    start_url: "/",
    display: "standalone",
    background_color: "#1a140e",
    theme_color: "#1a140e",
    icons: [
      {
        src: "/brand/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/brand/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
    ],
  };
}
